In [2]:
!pip install scikit-learn pandas tensorflow numpy
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv("heart.csv")
df

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [4]:
df.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [5]:
cat_columns = ['sex', 'cp', 'fbs', 'restecg', 'exng', 'slp', 'caa', 'thall', 'output']
df[cat_columns] = df[cat_columns].astype(str)

In [6]:
df = df.drop(columns=['output'])

In [7]:
df['thall'].unique()

array(['1', '2', '3', '0'], dtype=object)

In [8]:
df2 = pd.get_dummies(df, drop_first=True)
df2

age  trtbps  chol  thalachh  oldpeak  sex_1  cp_1  cp_2  cp_3  fbs_1  \
0     63     145   233       150      2.3      1     0     0     1      1   
1     37     130   250       187      3.5      1     0     1     0      0   
2     41     130   204       172      1.4      0     1     0     0      0   
3     56     120   236       178      0.8      1     1     0     0      0   
4     57     120   354       163      0.6      0     0     0     0      0   
..   ...     ...   ...       ...      ...    ...   ...   ...   ...    ...   
298   57     140   241       123      0.2      0     0     0     0      0   
299   45     110   264       132      1.2      1     0     0     1      0   
300   68     144   193       141      3.4      1     0     0     0      1   
301   57     130   131       115      1.2      1     0     0     0      0   
302   57     130   236       174      0.0      0     1     0     0      0   

     restecg_1  restecg_2  exng_1  slp_1  slp_2  caa_1  caa_2  caa_3  caa_4  \
0            0          0       0      0      0      0      0      0      0   
1            1          0       0      0      0      0      0      0      0   
2            0          0       0      0      1      0      0      0      0   
3            1          0       0      0      1      0      0      0      0   
4            1          0       1      0      1      0      0      0      0   
..         ...        ...     ...    ...    ...    ...    ...    ...    ...   
298          1          0       1      1      0      0      0      0      0   
299          1          0       0      1      0      0      0      0      0   
300          1          0       0      1      0      0      1      0      0   
301          1          0       1      1      0      1      0      0      0   
302          0          0       0      1      0      1      0      0      0   

     thall_1  thall_2  thall_3  
0          1        0        0  
1          0        1        0  
2          0        1        0  
3          0        1        0  
4          0        1        0  
..       ...      ...      ...  
298        0        0        1  
299        0        0        1  
300        0        0        1  
301        0        0        1  
302        0        1        0  

[303 rows x 22 columns]

In [9]:
df2.columns

Index(['age', 'trtbps', 'chol', 'thalachh', 'oldpeak', 'sex_1', 'cp_1', 'cp_2',
       'cp_3', 'fbs_1', 'restecg_1', 'restecg_2', 'exng_1', 'slp_1', 'slp_2',
       'caa_1', 'caa_2', 'caa_3', 'caa_4', 'thall_1', 'thall_2', 'thall_3'],
      dtype='object')

In [10]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x = sc.fit_transform(df2)

In [11]:
pd.DataFrame(x)

0         1         2         3         4         5         6   \
0    0.952197  0.763956 -0.256334  0.015443  1.087338  0.681005 -0.444554   
1   -1.915313 -0.092738  0.072199  1.633471  2.122573  0.681005 -0.444554   
2   -1.474158 -0.092738 -0.816773  0.977514  0.310912 -1.468418  2.249444   
3    0.180175 -0.663867 -0.198357  1.239897 -0.206705  0.681005  2.249444   
4    0.290464 -0.663867  2.082050  0.583939 -0.379244 -1.468418 -0.444554   
..        ...       ...       ...       ...       ...       ...       ...   
298  0.290464  0.478391 -0.101730 -1.165281 -0.724323 -1.468418 -0.444554   
299 -1.033002 -1.234996  0.342756 -0.771706  0.138373  0.681005 -0.444554   
300  1.503641  0.706843 -1.029353 -0.378132  2.036303  0.681005 -0.444554   
301  0.290464 -0.092738 -2.227533 -1.515125  0.138373  0.681005 -0.444554   
302  0.290464 -0.092738 -0.198357  1.064975 -0.896862 -1.468418  2.249444   

           7         8         9         10        11        12        13  \
0   -0.634648  3.489114  2.394438 -1.003306 -0.115663 -0.696631 -0.926766   
1    1.575677 -0.286606 -0.417635  0.996705 -0.115663 -0.696631 -0.926766   
2   -0.634648 -0.286606 -0.417635 -1.003306 -0.115663 -0.696631 -0.926766   
3   -0.634648 -0.286606 -0.417635  0.996705 -0.115663 -0.696631 -0.926766   
4   -0.634648 -0.286606 -0.417635  0.996705 -0.115663  1.435481 -0.926766   
..        ...       ...       ...       ...       ...       ...       ...   
298 -0.634648 -0.286606 -0.417635  0.996705 -0.115663  1.435481  1.079021   
299 -0.634648  3.489114 -0.417635  0.996705 -0.115663 -0.696631  1.079021   
300 -0.634648 -0.286606  2.394438  0.996705 -0.115663 -0.696631  1.079021   
301 -0.634648 -0.286606 -0.417635  0.996705 -0.115663  1.435481  1.079021   
302 -0.634648 -0.286606 -0.417635 -1.003306 -0.115663 -0.696631  1.079021   

           14        15        16        17        18        19        20  \
0   -0.939142 -0.522599 -0.378677 -0.265841 -0.129532  3.979112 -1.100763   
1   -0.939142 -0.522599 -0.378677 -0.265841 -0.129532 -0.251312  0.908461   
2    1.064802 -0.522599 -0.378677 -0.265841 -0.129532 -0.251312  0.908461   
3    1.064802 -0.522599 -0.378677 -0.265841 -0.129532 -0.251312  0.908461   
4    1.064802 -0.522599 -0.378677 -0.265841 -0.129532 -0.251312  0.908461   
..        ...       ...       ...       ...       ...       ...       ...   
298 -0.939142 -0.522599 -0.378677 -0.265841 -0.129532 -0.251312 -1.100763   
299 -0.939142 -0.522599 -0.378677 -0.265841 -0.129532 -0.251312 -1.100763   
300 -0.939142 -0.522599  2.640773 -0.265841 -0.129532 -0.251312 -1.100763   
301 -0.939142  1.913515 -0.378677 -0.265841 -0.129532 -0.251312 -1.100763   
302 -0.939142  1.913515 -0.378677 -0.265841 -0.129532 -0.251312  0.908461   

           21  
0   -0.793116  
1   -0.793116  
2   -0.793116  
3   -0.793116  
4   -0.793116  
..        ...  
298  1.260850  
299  1.260850  
300  1.260850  
301  1.260850  
302 -0.793116  

[303 rows x 22 columns]

In [12]:
np.array(df2.iloc[0])

array([ 63. , 145. , 233. , 150. ,   2.3,   1. ,   0. ,   0. ,   1. ,
         1. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
         0. ,   1. ,   0. ,   0. ])

In [13]:
sc.transform(np.array([df2.iloc[0]]))

/usr/local/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 0.9521966 ,  0.76395577, -0.25633371,  0.01544279,  1.08733806,
         0.68100522, -0.44455422, -0.63464776,  3.4891135 ,  2.394438  ,
        -1.00330579, -0.11566299, -0.69663055, -0.92676626, -0.93914194,
        -0.52259855, -0.37867694, -0.26584089, -0.12953194,  3.97911213,
        -1.10076284, -0.79311554]])

In [14]:
# ['age', 'trtbps', 'chol', 'thalachh', 'oldpeak', 'sex_1', 'cp_1', 'cp_2',
# 'cp_3', 'fbs_1', 'restecg_1', 'restecg_2', 'exng_1', 'slp_1', 'slp_2',
# 'caa_1', 'caa_2', 'caa_3', 'caa_4', 'thall_1', 'thall_2', 'thall_3']


# 'age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
#        'exng', 'oldpeak', 'slp', 'caa', 'thall'

In [15]:
def transform_row(age, trtbps, chol, thalachh, oldpeak, sex, cp, fbs, restecg, exng, slp, caa, thall):
    # yg di onehot perlu lebih lanjut: cp, restecg, slp, caa, thall
    # cp
    onehot_cp = [0,0,0]
    if cp == 3:
        onehot_cp[2] = 1
    elif cp == 2:
        onehot_cp[1] = 1
    elif cp == 1:
        onehot_cp[0] = 1
        
    #restecg
    onehot_restecg = [0,0]
    if restecg == 2:
        onehot_restecg[1] = 1
    elif restecg == 1:
        onehot_restecg[0] = 1
        
    #slp
    onehot_slp = [0,0]
    if slp == 2:
        onehot_slp[1] = 1
    elif slp == 1:
        onehot_slp[0] = 1
        
    #caa
    onehot_caa = [0,0,0,0]
    if caa == 4:
        onehot_caa[3] = 1
    elif caa == 3:
        onehot_caa[2] = 1
    elif caa == 2:
        onehot_caa[1] = 1
    elif caa == 1:
        onehot_caa[0] = 1
        
    #thall
    onehot_thall = [0,0,0]
    if thall == 2:
        onehot_thall[1] = 1
    elif thall == 1:
        onehot_thall[0] = 1
        
    row = [
        age,
        trtbps,
        chol,
        thalachh,
        oldpeak,
        sex,
        *onehot_cp,
        fbs,
        *onehot_restecg,
        exng,
        *onehot_slp,
        *onehot_caa,
        *onehot_thall
    ]
    
    return sc.transform(np.array([row]))

In [16]:
df.head()

age sex cp  trtbps  chol fbs restecg  thalachh exng  oldpeak slp caa thall
0   63   1  3     145   233   1       0       150    0      2.3   0   0     1
1   37   1  2     130   250   0       1       187    0      3.5   0   0     2
2   41   0  1     130   204   0       0       172    0      1.4   2   0     2
3   56   1  1     120   236   0       1       178    0      0.8   2   0     2
4   57   0  0     120   354   0       1       163    1      0.6   2   0     2

In [17]:
a = transform_row(63, 145, 233, 150, 2.3, 1, 3, 1, 0, 0, 0, 0, 1)

/usr/local/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [18]:
x[0]

array([ 0.9521966 ,  0.76395577, -0.25633371,  0.01544279,  1.08733806,
        0.68100522, -0.44455422, -0.63464776,  3.4891135 ,  2.394438  ,
       -1.00330579, -0.11566299, -0.69663055, -0.92676626, -0.93914194,
       -0.52259855, -0.37867694, -0.26584089, -0.12953194,  3.97911213,
       -1.10076284, -0.79311554])

In [19]:
x[0] == a

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True]])

In [20]:
import tensorflow as tf

model_heart = tf.keras.models.load_model('./models/heart_model.h5')


2022-12-19 17:09:09.080485: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [21]:
model_heart.predict(a)

1/1 [==============================] - 0s 207ms/step


array([[0.4787827]], dtype=float32)

In [22]:
df

age sex cp  trtbps  chol fbs restecg  thalachh exng  oldpeak slp caa  \
0     63   1  3     145   233   1       0       150    0      2.3   0   0   
1     37   1  2     130   250   0       1       187    0      3.5   0   0   
2     41   0  1     130   204   0       0       172    0      1.4   2   0   
3     56   1  1     120   236   0       1       178    0      0.8   2   0   
4     57   0  0     120   354   0       1       163    1      0.6   2   0   
..   ...  .. ..     ...   ...  ..     ...       ...  ...      ...  ..  ..   
298   57   0  0     140   241   0       1       123    1      0.2   1   0   
299   45   1  3     110   264   0       1       132    0      1.2   1   0   
300   68   1  0     144   193   1       1       141    0      3.4   1   2   
301   57   1  0     130   131   0       1       115    1      1.2   1   1   
302   57   0  1     130   236   0       0       174    0      0.0   1   1   

    thall  
0       1  
1       2  
2       2  
3       2  
4       2  
..    ...  
298     3  
299     3  
300     3  
301     3  
302     2  

[303 rows x 13 columns]

In [28]:
stroke_df =pd.read_csv('stroke.csv')
stroke_df

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5104  18234  Female  80.0             1              0          Yes   
5105  44873  Female  81.0             0              0          Yes   
5106  19723  Female  35.0             0              0          Yes   
5107  37544    Male  51.0             0              0          Yes   
5108  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5104        Private          Urban              83.75   NaN     never smoked   
5105  Self-employed          Urban             125.20  40.0     never smoked   
5106  Self-employed          Rural              82.99  30.6     never smoked   
5107        Private          Rural             166.29  25.6  formerly smoked   
5108       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5104       0  
5105       0  
5106       0  
5107       0  
5108       0  

[5109 rows x 12 columns]

In [29]:
stroke_cat_columns = ['gender', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'Residence_type', 'smoking_status', 'stroke']
stroke_df[stroke_cat_columns] = stroke_df[stroke_cat_columns].astype(str)
stroke_df['age'] = stroke_df['age'].astype(int)
stroke_df

id  gender  age hypertension heart_disease ever_married  \
0      9046    Male   67            0             1          Yes   
1     51676  Female   61            0             0          Yes   
2     31112    Male   80            0             1          Yes   
3     60182  Female   49            0             0          Yes   
4      1665  Female   79            1             0          Yes   
...     ...     ...  ...          ...           ...          ...   
5104  18234  Female   80            1             0          Yes   
5105  44873  Female   81            0             0          Yes   
5106  19723  Female   35            0             0          Yes   
5107  37544    Male   51            0             0          Yes   
5108  44679  Female   44            0             0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5104        Private          Urban              83.75   NaN     never smoked   
5105  Self-employed          Urban             125.20  40.0     never smoked   
5106  Self-employed          Rural              82.99  30.6     never smoked   
5107        Private          Rural             166.29  25.6  formerly smoked   
5108       Govt_job          Urban              85.28  26.2          Unknown   

     stroke  
0         1  
1         1  
2         1  
3         1  
4         1  
...     ...  
5104      0  
5105      0  
5106      0  
5107      0  
5108      0  

[5109 rows x 12 columns]

In [30]:
stroke_df = stroke_df.dropna()
stroke_df

id  gender  age hypertension heart_disease ever_married  \
0      9046    Male   67            0             1          Yes   
2     31112    Male   80            0             1          Yes   
3     60182  Female   49            0             0          Yes   
4      1665  Female   79            1             0          Yes   
5     56669    Male   81            0             0          Yes   
...     ...     ...  ...          ...           ...          ...   
5103  14180  Female   13            0             0           No   
5105  44873  Female   81            0             0          Yes   
5106  19723  Female   35            0             0          Yes   
5107  37544    Male   51            0             0          Yes   
5108  44679  Female   44            0             0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
5           Private          Urban             186.21  29.0  formerly smoked   
...             ...            ...                ...   ...              ...   
5103       children          Rural             103.08  18.6          Unknown   
5105  Self-employed          Urban             125.20  40.0     never smoked   
5106  Self-employed          Rural              82.99  30.6     never smoked   
5107        Private          Rural             166.29  25.6  formerly smoked   
5108       Govt_job          Urban              85.28  26.2          Unknown   

     stroke  
0         1  
2         1  
3         1  
4         1  
5         1  
...     ...  
5103      0  
5105      0  
5106      0  
5107      0  
5108      0  

[4908 rows x 12 columns]

In [182]:
stroke_df.iloc[40]

id                           35626
gender                        Male
age                             81
hypertension                     0
heart_disease                    0
ever_married                   Yes
work_type            Self-employed
Residence_type               Urban
avg_glucose_level            99.33
bmi                           33.7
smoking_status        never smoked
stroke                           1
Name: 48, dtype: object

In [183]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [184]:
stroke_label_encoder=LabelEncoder()

In [34]:
df_stroke_onehot = pd.get_dummies(stroke_df, drop_first=True)  # One-hot encode
df_stroke_onehot

id  age  avg_glucose_level   bmi  gender_Male  hypertension_1  \
0      9046   67             228.69  36.6            1               0   
2     31112   80             105.92  32.5            1               0   
3     60182   49             171.23  34.4            0               0   
4      1665   79             174.12  24.0            0               1   
5     56669   81             186.21  29.0            1               0   
...     ...  ...                ...   ...          ...             ...   
5103  14180   13             103.08  18.6            0               0   
5105  44873   81             125.20  40.0            0               0   
5106  19723   35              82.99  30.6            0               0   
5107  37544   51             166.29  25.6            1               0   
5108  44679   44              85.28  26.2            0               0   

      heart_disease_1  ever_married_Yes  work_type_Never_worked  \
0                   1                 1                       0   
2                   1                 1                       0   
3                   0                 1                       0   
4                   0                 1                       0   
5                   0                 1                       0   
...               ...               ...                     ...   
5103                0                 0                       0   
5105                0                 1                       0   
5106                0                 1                       0   
5107                0                 1                       0   
5108                0                 1                       0   

      work_type_Private  work_type_Self-employed  work_type_children  \
0                     1                        0                   0   
2                     1                        0                   0   
3                     1                        0                   0   
4                     0                        1                   0   
5                     1                        0                   0   
...                 ...                      ...                 ...   
5103                  0                        0                   1   
5105                  0                        1                   0   
5106                  0                        1                   0   
5107                  1                        0                   0   
5108                  0                        0                   0   

      Residence_type_Urban  smoking_status_formerly smoked  \
0                        1                               1   
2                        0                               0   
3                        1                               0   
4                        0                               0   
5                        1                               1   
...                    ...                             ...   
5103                     0                               0   
5105                     1                               0   
5106                     0                               0   
5107                     0                               1   
5108                     1                               0   

      smoking_status_never smoked  smoking_status_smokes  stroke_1  
0                               0                      0         1  
2                               1                      0         1  
3                               0                      1         1  
4                               1                      0         1  
5                               0                      0         1  
...                           ...                    ...       ...  
5103                            0                      0         0  
5105                            1                      0         0  
5106                            1                      0         0  
5107           

In [37]:
x_stroke = df_stroke_onehot.drop(columns=['id', 'stroke_1'])
x_stroke

age  avg_glucose_level   bmi  gender_Male  hypertension_1  \
0      67             228.69  36.6            1               0   
2      80             105.92  32.5            1               0   
3      49             171.23  34.4            0               0   
4      79             174.12  24.0            0               1   
5      81             186.21  29.0            1               0   
...   ...                ...   ...          ...             ...   
5103   13             103.08  18.6            0               0   
5105   81             125.20  40.0            0               0   
5106   35              82.99  30.6            0               0   
5107   51             166.29  25.6            1               0   
5108   44              85.28  26.2            0               0   

      heart_disease_1  ever_married_Yes  work_type_Never_worked  \
0                   1                 1                       0   
2                   1                 1                       0   
3                   0                 1                       0   
4                   0                 1                       0   
5                   0                 1                       0   
...               ...               ...                     ...   
5103                0                 0                       0   
5105                0                 1                       0   
5106                0                 1                       0   
5107                0                 1                       0   
5108                0                 1                       0   

      work_type_Private  work_type_Self-employed  work_type_children  \
0                     1                        0                   0   
2                     1                        0                   0   
3                     1                        0                   0   
4                     0                        1                   0   
5                     1                        0                   0   
...                 ...                      ...                 ...   
5103                  0                        0                   1   
5105                  0                        1                   0   
5106                  0                        1                   0   
5107                  1                        0                   0   
5108                  0                        0                   0   

      Residence_type_Urban  smoking_status_formerly smoked  \
0                        1                               1   
2                        0                               0   
3                        1                               0   
4                        0                               0   
5                        1                               1   
...                    ...                             ...   
5103                     0                               0   
5105                     1                               0   
5106                     0                               0   
5107                     0                               1   
5108                     1                               0   

      smoking_status_never smoked  smoking_status_smokes  
0                               0                      0  
2                               1                      0  
3                               0                      1  
4                               1                      0  
5                               0                      0  
...                           ...                    ...  
5103                            0                      0  
5105                            1                      0  
5106                            1                      0  
5107                            0                      0  
5108                            0                      0  

[4908 rows x 15 columns]

In [39]:
x_stroke.columns

Index(['age', 'avg_glucose_level', 'bmi', 'gender_Male', 'hypertension_1',
       'heart_disease_1', 'ever_married_Yes', 'work_type_Never_worked',
       'work_type_Private', 'work_type_Self-employed', 'work_type_children',
       'Residence_type_Urban', 'smoking_status_formerly smoked',
       'smoking_status_never smoked', 'smoking_status_smokes'],
      dtype='object')

In [38]:
sc_stroke = StandardScaler()
sc_stroke.fit_transform(x_stroke)

array([[ 1.06944573,  2.77779723,  0.98114481, ...,  2.20699193,
        -0.77847347, -0.42035251],
       [ 1.64531154,  0.01401584,  0.45908589, ..., -0.45310542,
         1.28456529, -0.42035251],
       [ 0.27209307,  1.48426559,  0.70101563, ..., -0.45310542,
        -0.77847347,  2.37895568],
       ...,
       [-0.3480701 , -0.50218118,  0.21715615, ..., -0.45310542,
         1.28456529, -0.42035251],
       [ 0.36068781,  1.37305699, -0.41950107, ...,  2.20699193,
        -0.77847347, -0.42035251],
       [ 0.05060623, -0.45062901, -0.3431022 , ..., -0.45310542,
        -0.77847347, -0.42035251]])

In [40]:
import tensorflow as tf

model_stroke = tf.keras.models.load_model('./models/stroke_model2.h5')

In [193]:
sr = df_stroke_onehot.iloc[1].drop(['id', 'stroke_1'])
a = np.array([sr])
b = sc_stroke.transform(a)
print(b)
model_stroke.predict(b)

[[ 1.64531154  0.01401584  0.45908589  1.20024032 -0.31810241  4.3814987
   0.72927032 -0.06710187  0.8640713  -0.43303016 -0.39795322 -1.01477913
  -0.45310542  1.28456529 -0.42035251]]
1/1 [==============================] - 0s 33ms/step


/usr/local/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[0.5902416]], dtype=float32)

In [194]:
coba = stroke_df.iloc[3]
coba

id                            1665
gender                      Female
age                             79
hypertension                     1
heart_disease                    0
ever_married                   Yes
work_type            Self-employed
Residence_type               Rural
avg_glucose_level           174.12
bmi                           24.0
smoking_status        never smoked
stroke                           1
Name: 4, dtype: object

In [207]:
stroke_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4908 entries, 0 to 5108
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 4908 non-null   int64  
 1   gender             4908 non-null   object 
 2   age                4908 non-null   int64  
 3   hypertension       4908 non-null   object 
 4   heart_disease      4908 non-null   object 
 5   ever_married       4908 non-null   object 
 6   work_type          4908 non-null   object 
 7   Residence_type     4908 non-null   object 
 8   avg_glucose_level  4908 non-null   float64
 9   bmi                4908 non-null   float64
 10  smoking_status     4908 non-null   object 
 11  stroke             4908 non-null   object 
dtypes: float64(2), int64(2), object(8)
memory usage: 498.5+ KB


In [208]:
df1 = pd.get_dummies(pd.DataFrame({
    'gender':[coba['gender']],
    'age':[coba['age']],
    'hypertension': [coba['hypertension']],
    'heart_disease': [coba['heart_disease']],
    'ever_married': [coba['ever_married']],
    'work_type': [coba['work_type']],
    'Residence_type': [coba['Residence_type']],
    'avg_glucose_level': [coba['avg_glucose_level']],
    'bmi': [coba['bmi']],
    'smoking_status': [coba['smoking_status']],
}))
df1

age  avg_glucose_level   bmi  gender_Female  hypertension_1  \
0   79             174.12  24.0              1               1   

   heart_disease_0  ever_married_Yes  work_type_Self-employed  \
0                1                 1                        1   

   Residence_type_Rural  smoking_status_never smoked  
0                     1                            1

In [209]:
innn_1 = df1.reindex(columns = df_stroke_onehot.columns, fill_value=0).drop(columns=['id', 'stroke_1'])
innn_1

age  avg_glucose_level   bmi  gender_Male  hypertension_1  heart_disease_1  \
0   79             174.12  24.0            0               1                0   

   ever_married_Yes  work_type_Never_worked  work_type_Private  \
0                 1                       0                  0   

   work_type_Self-employed  work_type_children  Residence_type_Urban  \
0                        1                   0                     0   

   smoking_status_formerly smoked  smoking_status_never smoked  \
0                               0                            1   

   smoking_status_smokes  
0                      0

In [210]:
innn_3 = sc_stroke.transform(innn_1)
innn_3

array([[ 1.60101417,  1.54932488, -0.62323138, -0.83316648,  3.14364174,
        -0.22823241,  0.72927032, -0.06710187, -1.1573119 ,  2.30930795,
        -0.39795322, -1.01477913, -0.45310542,  1.28456529, -0.42035251]])

[[-1.89847805 -2.37044067 -3.67918601 -0.83316648 -0.31810241 -0.22823241
   0.72927032 -0.06710187  0.8640713  -0.43303016 -0.39795322  0.98543612
  -0.45310542 -0.77847347  2.37895568]]

In [211]:
model_stroke.predict(innn_3)

1/1 [==============================] - 0s 21ms/step


array([[0.60522276]], dtype=float32)