In [ ]:
!pip install scikit-learn pandas tensorflow numpy
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [46]:
df = pd.read_csv("h.csv")
df

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [68]:
df.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall'],
      dtype='object')

In [47]:
cat_columns = ['sex', 'cp', 'fbs', 'restecg', 'exng', 'slp', 'caa', 'thall', 'output']
df[cat_columns] = df[cat_columns].astype(str)

In [48]:
df = df.drop(columns=['output'])

In [112]:
df['thall'].unique()

array(['1', '2', '3', '0'], dtype=object)

In [49]:
df2 = pd.get_dummies(df, drop_first=True)
df2

age  trtbps  chol  thalachh  oldpeak  sex_1  cp_1  cp_2  cp_3  fbs_1  \
0     63     145   233       150      2.3      1     0     0     1      1   
1     37     130   250       187      3.5      1     0     1     0      0   
2     41     130   204       172      1.4      0     1     0     0      0   
3     56     120   236       178      0.8      1     1     0     0      0   
4     57     120   354       163      0.6      0     0     0     0      0   
..   ...     ...   ...       ...      ...    ...   ...   ...   ...    ...   
298   57     140   241       123      0.2      0     0     0     0      0   
299   45     110   264       132      1.2      1     0     0     1      0   
300   68     144   193       141      3.4      1     0     0     0      1   
301   57     130   131       115      1.2      1     0     0     0      0   
302   57     130   236       174      0.0      0     1     0     0      0   

     restecg_1  restecg_2  exng_1  slp_1  slp_2  caa_1  caa_2  caa_3  caa_4  \
0            0          0       0      0      0      0      0      0      0   
1            1          0       0      0      0      0      0      0      0   
2            0          0       0      0      1      0      0      0      0   
3            1          0       0      0      1      0      0      0      0   
4            1          0       1      0      1      0      0      0      0   
..         ...        ...     ...    ...    ...    ...    ...    ...    ...   
298          1          0       1      1      0      0      0      0      0   
299          1          0       0      1      0      0      0      0      0   
300          1          0       0      1      0      0      1      0      0   
301          1          0       1      1      0      1      0      0      0   
302          0          0       0      1      0      1      0      0      0   

     thall_1  thall_2  thall_3  
0          1        0        0  
1          0        1        0  
2          0        1        0  
3          0        1        0  
4          0        1        0  
..       ...      ...      ...  
298        0        0        1  
299        0        0        1  
300        0        0        1  
301        0        0        1  
302        0        1        0  

[303 rows x 22 columns]

In [50]:
df2.columns

Index(['age', 'trtbps', 'chol', 'thalachh', 'oldpeak', 'sex_1', 'cp_1', 'cp_2',
       'cp_3', 'fbs_1', 'restecg_1', 'restecg_2', 'exng_1', 'slp_1', 'slp_2',
       'caa_1', 'caa_2', 'caa_3', 'caa_4', 'thall_1', 'thall_2', 'thall_3'],
      dtype='object')

In [116]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x = sc.fit_transform(df2)

In [53]:
pd.DataFrame(x)

0         1         2         3         4         5         6   \
0    0.952197  0.763956 -0.256334  0.015443  1.087338  0.681005 -0.444554   
1   -1.915313 -0.092738  0.072199  1.633471  2.122573  0.681005 -0.444554   
2   -1.474158 -0.092738 -0.816773  0.977514  0.310912 -1.468418  2.249444   
3    0.180175 -0.663867 -0.198357  1.239897 -0.206705  0.681005  2.249444   
4    0.290464 -0.663867  2.082050  0.583939 -0.379244 -1.468418 -0.444554   
..        ...       ...       ...       ...       ...       ...       ...   
298  0.290464  0.478391 -0.101730 -1.165281 -0.724323 -1.468418 -0.444554   
299 -1.033002 -1.234996  0.342756 -0.771706  0.138373  0.681005 -0.444554   
300  1.503641  0.706843 -1.029353 -0.378132  2.036303  0.681005 -0.444554   
301  0.290464 -0.092738 -2.227533 -1.515125  0.138373  0.681005 -0.444554   
302  0.290464 -0.092738 -0.198357  1.064975 -0.896862 -1.468418  2.249444   

           7         8         9         10        11        12        13  \
0   -0.634648  3.489114  2.394438 -1.003306 -0.115663 -0.696631 -0.926766   
1    1.575677 -0.286606 -0.417635  0.996705 -0.115663 -0.696631 -0.926766   
2   -0.634648 -0.286606 -0.417635 -1.003306 -0.115663 -0.696631 -0.926766   
3   -0.634648 -0.286606 -0.417635  0.996705 -0.115663 -0.696631 -0.926766   
4   -0.634648 -0.286606 -0.417635  0.996705 -0.115663  1.435481 -0.926766   
..        ...       ...       ...       ...       ...       ...       ...   
298 -0.634648 -0.286606 -0.417635  0.996705 -0.115663  1.435481  1.079021   
299 -0.634648  3.489114 -0.417635  0.996705 -0.115663 -0.696631  1.079021   
300 -0.634648 -0.286606  2.394438  0.996705 -0.115663 -0.696631  1.079021   
301 -0.634648 -0.286606 -0.417635  0.996705 -0.115663  1.435481  1.079021   
302 -0.634648 -0.286606 -0.417635 -1.003306 -0.115663 -0.696631  1.079021   

           14        15        16        17        18        19        20  \
0   -0.939142 -0.522599 -0.378677 -0.265841 -0.129532  3.979112 -1.100763   
1   -0.939142 -0.522599 -0.378677 -0.265841 -0.129532 -0.251312  0.908461   
2    1.064802 -0.522599 -0.378677 -0.265841 -0.129532 -0.251312  0.908461   
3    1.064802 -0.522599 -0.378677 -0.265841 -0.129532 -0.251312  0.908461   
4    1.064802 -0.522599 -0.378677 -0.265841 -0.129532 -0.251312  0.908461   
..        ...       ...       ...       ...       ...       ...       ...   
298 -0.939142 -0.522599 -0.378677 -0.265841 -0.129532 -0.251312 -1.100763   
299 -0.939142 -0.522599 -0.378677 -0.265841 -0.129532 -0.251312 -1.100763   
300 -0.939142 -0.522599  2.640773 -0.265841 -0.129532 -0.251312 -1.100763   
301 -0.939142  1.913515 -0.378677 -0.265841 -0.129532 -0.251312 -1.100763   
302 -0.939142  1.913515 -0.378677 -0.265841 -0.129532 -0.251312  0.908461   

           21  
0   -0.793116  
1   -0.793116  
2   -0.793116  
3   -0.793116  
4   -0.793116  
..        ...  
298  1.260850  
299  1.260850  
300  1.260850  
301  1.260850  
302 -0.793116  

[303 rows x 22 columns]

In [64]:
np.array(df2.iloc[0])

array([ 63. , 145. , 233. , 150. ,   2.3,   1. ,   0. ,   0. ,   1. ,
         1. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
         0. ,   1. ,   0. ,   0. ])

In [66]:
sc.transform(np.array([df2.iloc[0]]))

/Users/hariangr/Documents/MyFiles/Developer/Joki/gmiyas/venv/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 0.9521966 ,  0.76395577, -0.25633371,  0.01544279,  1.08733806,
         0.68100522, -0.44455422, -0.63464776,  3.4891135 ,  2.394438  ,
        -1.00330579, -0.11566299, -0.69663055, -0.92676626, -0.93914194,
        -0.52259855, -0.37867694, -0.26584089, -0.12953194,  3.97911213,
        -1.10076284, -0.79311554]])

In [67]:
# ['age', 'trtbps', 'chol', 'thalachh', 'oldpeak', 'sex_1', 'cp_1', 'cp_2',
# 'cp_3', 'fbs_1', 'restecg_1', 'restecg_2', 'exng_1', 'slp_1', 'slp_2',
# 'caa_1', 'caa_2', 'caa_3', 'caa_4', 'thall_1', 'thall_2', 'thall_3']


# 'age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
#        'exng', 'oldpeak', 'slp', 'caa', 'thall'

In [117]:
def transform_row(age, trtbps, chol, thalachh, oldpeak, sex, cp, fbs, restecg, exng, slp, caa, thall):
    # yg di onehot perlu lebih lanjut: cp, restecg, slp, caa, thall
    # cp
    onehot_cp = [0,0,0]
    if cp == 3:
        onehot_cp[2] = 1
    elif cp == 2:
        onehot_cp[1] = 1
    elif cp == 1:
        onehot_cp[0] = 1
        
    #restecg
    onehot_restecg = [0,0]
    if restecg == 2:
        onehot_restecg[1] = 1
    elif restecg == 1:
        onehot_restecg[0] = 1
        
    #slp
    onehot_slp = [0,0]
    if slp == 2:
        onehot_slp[1] = 1
    elif slp == 1:
        onehot_slp[0] = 1
        
    #caa
    onehot_caa = [0,0,0,0]
    if caa == 4:
        onehot_caa[3] = 1
    elif caa == 3:
        onehot_caa[2] = 1
    elif caa == 2:
        onehot_caa[1] = 1
    elif caa == 1:
        onehot_caa[0] = 1
        
    #thall
    onehot_thall = [0,0,0]
    if thall == 2:
        onehot_thall[1] = 1
    elif thall == 1:
        onehot_thall[0] = 1
        
    row = [
        age,
        trtbps,
        chol,
        thalachh,
        oldpeak,
        sex,
        *onehot_cp,
        fbs,
        *onehot_restecg,
        exng,
        *onehot_slp,
        *onehot_caa,
        *onehot_thall
    ]
    
    return sc.transform(np.array([row]))

In [118]:
df.head()

age sex cp  trtbps  chol fbs restecg  thalachh exng  oldpeak slp caa thall
0   63   1  3     145   233   1       0       150    0      2.3   0   0     1
1   37   1  2     130   250   0       1       187    0      3.5   0   0     2
2   41   0  1     130   204   0       0       172    0      1.4   2   0     2
3   56   1  1     120   236   0       1       178    0      0.8   2   0     2
4   57   0  0     120   354   0       1       163    1      0.6   2   0     2

In [125]:
a = transform_row(63, 145, 233, 150, 2.3, 1, 3, 1, 0, 0, 0, 0, 1)

/Users/hariangr/Documents/MyFiles/Developer/Joki/gmiyas/venv/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [126]:
x[0]

array([ 0.9521966 ,  0.76395577, -0.25633371,  0.01544279,  1.08733806,
        0.68100522, -0.44455422, -0.63464776,  3.4891135 ,  2.394438  ,
       -1.00330579, -0.11566299, -0.69663055, -0.92676626, -0.93914194,
       -0.52259855, -0.37867694, -0.26584089, -0.12953194,  3.97911213,
       -1.10076284, -0.79311554])

In [128]:
x[0] == a

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True]])

In [129]:
import tensorflow as tf

model_heart = tf.keras.models.load_model('./models/heart_model.h5')


2022-12-16 22:15:31.412418: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-16 22:15:37.275455: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [130]:
model_heart.predict(a)

1/1 [==============================] - 0s 239ms/step


array([[0.4787827]], dtype=float32)

In [131]:
df

age sex cp  trtbps  chol fbs restecg  thalachh exng  oldpeak slp caa  \
0     63   1  3     145   233   1       0       150    0      2.3   0   0   
1     37   1  2     130   250   0       1       187    0      3.5   0   0   
2     41   0  1     130   204   0       0       172    0      1.4   2   0   
3     56   1  1     120   236   0       1       178    0      0.8   2   0   
4     57   0  0     120   354   0       1       163    1      0.6   2   0   
..   ...  .. ..     ...   ...  ..     ...       ...  ...      ...  ..  ..   
298   57   0  0     140   241   0       1       123    1      0.2   1   0   
299   45   1  3     110   264   0       1       132    0      1.2   1   0   
300   68   1  0     144   193   1       1       141    0      3.4   1   2   
301   57   1  0     130   131   0       1       115    1      1.2   1   1   
302   57   0  1     130   236   0       0       174    0      0.0   1   1   

    thall  
0       1  
1       2  
2       2  
3       2  
4       2  
..    ...  
298     3  
299     3  
300     3  
301     3  
302     2  

[303 rows x 13 columns]